### ISSUE TITLE
关于heads.npy中的数据是怎么生成的

### ISSUE THREAD

**Issue by HeYuwei9** [Yasoz/DiffTraj#1]
请问[depature, total_dis, total_time, total_len, avg_dis, avg_speed, sid, eid]这些属性是怎么计算的呢？
heads.npy中的数量和轨迹数量相同，是哪一个时间的chengdu数据呀
期待收到您的回复，这将对我很有帮助！

**Comment by Yasoz** [comment]
你好，[depature, total_dis, total_time, total_len, avg_dis, avg_speed]均为数据自带的属性，sid, eid可以理解为将城市划为网格状后，对应的起点终点编码。这里面提供的heads.npy数据是随机采样了一部分，没有具体对应哪一时间段。谢谢！

**Comment by HeYuwei9** [comment]
网上找的数据集没有这些属性🥹🥹，您能提供一下源数据集吗，这将对我的研究十分有帮助！̋(ˊ•͈ꇴ•͈ˋ)

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年11月07日 10:35 |
| 收件人 | Yasoz/DiffTraj ***@***.***> |
| 抄送人 | HeYuwei9 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [Yasoz/DiffTraj] 关于heads.npy中的数据是怎么生成的 (Issue #1) |

你好，[depature, total_dis, total_time, total_len, avg_dis, avg_speed]均为数据自带的属性，sid, eid可以理解为将城市划为网格状后，对应的起点终点编码。这里面提供的heads.npy数据是随机采样了一部分，没有具体对应哪一时间段。谢谢！

**Comment by Yasoz** [comment]
这些属性可以通过计算得到，数据集需要授权才能公开，很抱歉。获取你可以参考这个https://github.com/Yasoz/SynMob

**Comment by Yasoz** [comment]
Thanks for your interest. 

Yes, we divide the departure time into 5-minute intervals, so it has 288 categorical. The total_len feature is used to record the length of GPS points. total_dis and total_time are denoted by the distance and travel time for a trip, respectively.

> Hi there, thank you so much for making your code available.
> 
> I have access to the Didi Chuxing dataset and also had some questions regarding the properties within the head.npy dataset. Since departure is a categorical feature (288 range), is this the day divided into 5 minute intervals? Also could you explain what the total_len feature is measuring if we already have total_dis, and total_time?
> 
> Thanks in advance!

**Comment by zxzx-hub** [comment]
作者你好，我能访问您所用的数据集。我想请问如果depature所代表的是开始计费时间和结束计费时间的插值吗？如果是那么大于288的数据是不是要去掉？或者您能告诉我您是怎么处理数据的吗？
