### ISSUE TITLE
Training Duration - Number of Steps / Epochs

### ISSUE THREAD

**Issue by erik-buchholz** [Yasoz/DiffTraj#16]
Dear Yuanshao,

I have a short question regarding the duration of the training. How long did you train for on the different datasets? The config (utils/config.py) contains both n_epochs (`=200`) and n_iters (`=5 000 000`) which are conflicting?
For instance, on Chengdu: 

200 epochs = 3 493 918 / 1024 * 200 = 682 405 iterations

What did you use in your evaluation, the 200epochs or the n_iters values, or something completely different? I would like to run your model on another dataset and stay as close as possible to your results in order to allow for a fair comparison.

Thanks a lot for your help!

Cheers,
Erik

**Comment by Yasoz** [comment]
Hi Erik,

The  n_iters is not used in this project. This parameter was kept in the original code base, and I am sorry for forgetting to delete it. I only used the epoch here.

Best,
Yuanshao

**Comment by erik-buchholz** [comment]
Hi Yuanshao,

Thank you so much for confirming this!
Did you use 200 epochs for both your datasets, or did you use 200 epochs only on Chengu but used a different number of epochs for Xi'an?

BTW. I finally managed to get your model to work on my dataset. Thank you so much for your help!

Cheers,
Erik

**Comment by Yasoz** [comment]
Both datasets use 200 epoches. Actually, 100 epochs is sufficient to get good results.

Best,
Yuanshao
