### ISSUE TITLE
Standardisation of data in example head.npy provided

### ISSUE THREAD

**Issue by FerOroC** [Yasoz/DiffTraj#6]
I see in the example head data snippet provided for the Traj_Generation.ipynb that some of the columns have been standardised (all bar the first and last two columns pertaining to time start interval, sid, and eid). 

Is this something we have to do to the input head dataset for the model? I am trying to replicate your results on the Chengdu dataset, but do not have access to the head.npy dataset so am deriving it from the trajectory dataset. Thanks in advance.

**Comment by Yasoz** [comment]
Hello, I'm just following the general practice here. I think it can isolate the effects caused by the numerical magnitude of the different attributes.

**Comment by Pursue1221** [comment]
Could you please provide the calculation method of head.npy? Thanks in advance.
