### ISSUE TITLE
different lengths of trajectory data

### ISSUE THREAD

**Issue by dixinyinli2** [Yasoz/DiffTraj#8]
The trajectory data of real world is different in lengths, I wonder how you tackle the problem during training. Looking forward to your reply, thanks.

**Comment by bonjer-26** [comment]
Yes. I also faced the same problem. is it something padded or interpolated?

**Comment by CharlotteE67** [comment]
> "... Considering CNN-based models can only accept fixed-shape data, we initially up-sample or down-sample the training trajectories using linear interpolation methods [3]. The generated trajectories are then transformed to the desired length using the same approach." 

As the paper mentions, I think the trajectory data is processed and the length is set to 200 as one of the hyperparameters, which can be found in Appendix A.2.
